package pretty_errors

private const val ESC = "\u001b"
const val ANSI_RESET = "$ESC[39m"
const val ANSI_BLACK = "$ESC[30m"
const val ANSI_RED = "$ESC[31m"
const val ANSI_GREEN = "$ESC[32m"
const val ANSI_YELLOW = "$ESC[33m"
const val ANSI_BLUE = "$ESC[34m"
const val ANSI_MAGENTA = "$ESC[35m"
const val ANSI_CYAN = "$ESC[36m"
const val ANSI_LIGHT_GRAY = "$ESC[37m"
const val ANSI_DARK_GRAY = "$ESC[90m"
const val ANSI_LIGHT_RED = "$ESC[91m"
const val ANSI_LIGHT_GREEN = "$ESC[92m"
const val ANSI_LIGHT_YELLOW = "$ESC[93m"
const val ANSI_LIGHT_BLUE = "$ESC[94m"
const val ANSI_PINK = "$ESC[95m"
const val ANSI_LIGHT_CYAN = "$ESC[96m"
const val ANSI_WHITE = "$ESC[97m"